on: [push, pull_request]

name: Test
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ^14
      - run: npm i
      - run: npm run compile
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
